from pydantic import BaseModel, Field
from datetime import date

# ---------------------------------------------------------
#Payment Behavior Analysis API Schemas
# ---------------------------------------------------------
class PaymentSummaryRequest(BaseModel):
    start_date: date = Field(..., example="2026-01-01", description="Start date for the analysis (YYYY-MM-DD)")
    end_date: date = Field(..., example="2026-03-31", description="End date for the analysis (YYYY-MM-DD)")

class PaymentSummaryResponse(BaseModel):
    summary: str = Field(..., description="Natural language summary of payment behavior generated by AI")


# ---------------------------------------------------------
#AI Fraud Risk Explanation API Schemas
# ---------------------------------------------------------
class FraudRiskRequest(BaseModel):
    transaction_id: str = Field(..., example="TX10021", description="The ID of the transaction to analyze for fraud risk")

class FraudRiskResponse(BaseModel):
    risk_score: str = Field(..., example="High", description="Calculated risk level (Low / Medium / High)")
    explanation: str = Field(..., description="AI-generated explanation of WHY the transaction is risky")
    recommendation: str = Field(..., example="block", description="Suggested action (approve / review / block)")


# ---------------------------------------------------------
# AI Smart Payment Query API Schemas
# ---------------------------------------------------------
class PaymentAskRequest(BaseModel):
    question: str = Field(
        ..., 
        example="Why are payment failures increasing this month?", 
        description="Natural language question regarding payment data"
    )

class PaymentAskResponse(BaseModel):
    answer: str = Field(..., description="Business-friendly, AI-generated answer based on data context")


# ---------------------------------------------------------
# Payment Recommendation Engine API Schemas
# ---------------------------------------------------------

class PaymentRecommendationResponse(BaseModel):
    insights: str = Field(..., description="AI-generated suggestions for payment gateways, retries, and fraud prevention")